### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by marcusklaas** [ogham/rust-number-prefix#2]
Mostly of the form

```
warning: the trait `core::marker::Sized` is not implemented for the type `Self` [E0277]
```

. The compiler warns that this will be a hard error in the next stable version.

**Comment by ogham** [comment]
Could I get your `rustc --version` please? I'm not seeing these warnings on stable or nightly.

**Comment by marcusklaas** [comment]
Woops, I attributed this warning to the wrong project. Apologies, and thanks for the awesome crate!

**Comment by ogham** [comment]
hehe! thanks :+1:
