### ISSUE TITLE
mibi vs mebi

### ISSUE THREAD

**Issue by de-vri-es** [ogham/rust-number-prefix#7]
The official `2^20` prefix is called `mebi` as defined by the ISO and the IEC, not `mibi` [1][2]. To be honest I also always though it was `mibi`, but apparantly it is not. `MiB` is somewhat misleading here.

Since it's now part of the API, changing it would be backwards incompatible. So I'm not sure what or if you want to do anything about it.

[1] https://physics.nist.gov/cuu/Units/binary.html
[2] https://en.wikipedia.org/wiki/Units_of_information#Systematic_multiples

**Comment by ogham** [comment]
Blow me down, I had no idea! I must have seen the `Mi` prefix, guessed, then somehow never looked at the list.

I ended up changing it in the code then bumping the version from v0.3 to v0.4 to reflect the backwards incompatibility. It doesn't look like I can offer an enum alias or deprecate the old variant. Hopefully this is a small enough change that it will be clear what happened.

There are several changes this release ([documented here](https://github.com/ogham/rust-number-prefix/releases/tag/v0.4.0)) and now they're done in one go.
